#: include LoginScreen screens_login.LoginScreen
#: include LaboratorioScreen screens_laboratorio.LaboratorioScreen
#: include PerfilScreen  screens_perfil.PerfilScreen
#: include AcompanharScreen screens_acompanhar.AcompanharScreen
#: include HomeEmpresaScreen screens_empresa.HomeEmpresaScreen

<MainScreenManager>
    LoginScreen:
    AcompanharScreen: 
    LaboratorioScreen:
    PerfilScreen:
    HomeEmpresaScreen:
